routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
    Alert::success('Hello');
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

// Route::delete('/products/create/{id}', 'ProductController@store')->name('products.store');
Route::delete('/cart', 'CartController@clearAll')->name('cart.clearAll');

Route::resources([
	'categories' => 'CategoryController',
	'products' => 'ProductController',
	'cart' => 'CartController',
	'transactions' => 'TransactionController',
	'dashboards' => 'DashboardController'
]);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
	use SoftDeletes;
    protected $fillable = ["name", "available", "total"];

    public function products(){
    	return $this->hasMany('App\Product');
    	
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use App\Product_status;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('viewAny', Category::class);
        $categories = Category::all()->sortBy('name');
        $products = Product::all()->sortBy('name');

        // foreach ($categories as $category) {
        //     $category->total = DB::table('categories')
        //         ->where('category_id', $category->id)
        //         ->count();
        //     $category->save();
        // }

        // foreach ($categories as $category) {
        //     $category->available = DB::table('categories')
        //         ->where('category_id', $category->id)
        //         ->where('product_statuses_id', 1)
        //         ->count();
        //     $category->save();
        // }        


        return view('categories.index')
            ->with('products', $products)
            ->with('categories', $categories);
            
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Category::class);
        return view('categories.index');

        //

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Category::class);
        $validatedData = $request->validate([
            'name' =>'required|unique:categories,name'
        ]);

        $category = new Category($validatedData);
        $category->save();

        return redirect(route('categories.index'))
            ->with('success',"Item $category->name is added successfully")
            ->with('alert','warning');
            // ->with('product', $product);

        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $this->authorize('view', $category);

        $products = Product::all();
        $count = collect($products)->where('category_id', $category->id)
            ->where('product_status_id', 1)->count();
        $count_total = collect($products)->where('category_id', $category->id)->count();

        $products = Product::all();
         return view('categories.show')
            ->with('count', $count)
            ->with('count_total', $count_total)
            ->with('category', $category)
            ->with('products', Product::all()->where('category_id', $category->id))
            ->with('product_statuses', Product_status::all());
             // ->with('products', $products);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $this->authorize('update', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->authorize('update', $category);
         $validatedData = $request->validate([
            'name' =>'required|unique:categories,name'
        ]);
        $category->update($validatedData);
        $category->save();


        return redirect(route('categories.index', $category->id))
            ->with('success', "Item $category->name is updated successfully.");
            // ->with('product', $product);


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $this->authorize('delete', $category);

        $products = Product::all();
        $count_total = collect($products)->where('category_id', $category->id)->count();
        if($count_total === 0) {
            $category->delete();
            return redirect(route('categories.index'))
                ->with('success',"Item $category->name has been deleted")
                ->with('alert','warning');
        }
            return back()
                ->with('success', 'Item has a product left, cannot be deleted.');

        //

    }
}

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container-fluid py-5" id="category-index">
		{{-- alert-message --}}
		@includeWhen(Session::has('message'),'partials.alert')
		{{-- end alert message --}}
		
		<div class="row">
		@can('isAdmin')
		  <div class="col-4">
			    <div class="list-group" id="list-tab" role="tablist">
			      <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">All items</a>
			      	<a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Create new item</a>
			    </div>
		  </div>
		@endcan
		<div class="col-8 mx-auto">
		    <div class="tab-content" id="nav-tabContent">
		      <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
		      	<div class="row">
					
					@foreach($categories as $category)
						<?php $count = collect($products)->where('category_id', $category->id) 
							->where('product_status_id', 1)->count();
							$count_total = collect($products)->where('category_id', $category->id)
							->count();

						?>
						{{-- card start --}}
						<div class="col-12 col-sm-6 col-md-4 col-lg-3">
							@include('categories.partials.card')
						</div>
						{{-- card end --}}
					@endforeach
					@include('sweetalert::alert')
				</div>
			</div>
		      <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">
		      	<div class="container">
				<div class="row">
					<div class="col-12">
						<h1 class="text-center text-white">
							Create New Item
						</h1>
					</div>
				</div>

				{{-- start form section --}}
				<div class="row">
					<div class="col-12 col-sm-6 mx-auto">
						<form action="{{ route('categories.store') }}" method="post">
							@csrf
							<label for="name" class="text-white font-weight-bold">Name:</label>
							<input type="text" name="name" id="name" required class="form-control form-control-sm">
							<button class="btn btn-sm btn-primary mt-1">Add Item</button>
						</form>
					</div>
					@include('sweetalert::alert')
				</div>
				{{-- end form section --}}
			</div>
		      </div>
		      <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">...</div>
		      <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">...</div>
		    </div>
		  </div>
		</div>



		{{-- category list start --}}
		
		{{-- category list end --}}
	</div>
@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container my-4">
	<div class="row">
		<div class="col-12 col-md-4 col-lg-3 mx-auto">
			@include('categories.partials.card', ['view' => false])

			@includeWhen(Session::has('message'), 'partials.alert')
			
			@can('isAdmin')
			<div class="my-3">
				<form 
					action="{{ route('products.store') }}" 
					method="post" 
					enctype="multipart/form-data"

				>
					@csrf
					
					<?php $product_code = strtoupper(Str::random(10)) ?>

					<h5 class="text-center">Create Unit</h5>

					<label for="product_code">Unit Code:</label>
					<div class="input-group mb-3">

						<div class="input-group-prepend">
							<span class="input-group-text" id="product_code">{{$category->id}}-</span>
						</div>
						<input type="text" id="product_code" name="product_code" value="{{$product_code}}" class="form-control" placeholder="{{$product_code}}" aria-label="product_code" aria-describedby="basic-addon1">
					</div>



					{{-- name --}}
					@include('products.partials.form-group',[
							'name' => 'name',
							'type' => 'text',
							'classes' => ['form-control', 'form-control-sm']
					])


					{{-- category id--}}
					<label for="category_id">Unit Category:</label>
					<select name="category_id" id="category_id" class="form-control form-control-sm">
						<option value="{{ $category->id }}">{{ $category->name }}</option>
					</select>
					

					{{-- image --}}
					@include('products.partials.form-group',[
							'name' => 'image',
							'type' => 'file',
							'classes' => ['form-control-file', 'form-control-sm']
					])

					{{-- description --}}
					<label class="mt-3" for="description">Unit Description:</label>
					<textarea 
						name="description" 
						id="description" cols="30" 
						rows="10" 
						class="form-control 
							form-control-sm 
							@error('description') is-invalid @enderror
						"
						
						></textarea>
					@error('description')
					<small class="d-block invalid-feedback">
						<strong>
							{{ $message }}
						</strong>
					</small>
					@enderror
					<button class="btn btn-sm btn-primary mt-3 w-100">
						<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-folder-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M9.828 4H2.19a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91H9v1H2.826a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31L.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181L15.546 8H14.54l.265-2.91A1 1 0 0 0 13.81 4H9.828zm-2.95-1.707L7.587 3H2.19c-.24 0-.47.042-.684.12L1.5 2.98a1 1 0 0 1 1-.98h3.672a1 1 0 0 1 .707.293z"/>
							<path fill-rule="evenodd" d="M13.5 10a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H13v-1.5a.5.5 0 0 1 .5-.5z"/>
							<path fill-rule="evenodd" d="M13 12.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0v-2z"/>
						</svg>
						Add Unit
					</button>
				</form>
			</div>
			@endcan                      
		</div>
		<div class="col-12 col-md-8 col-lg-9">
			<div class="row">
				@foreach($products as $product)
					@if($category->id === $product->category_id )
					{{-- product card start --}}
						<div class="col-12 col-sm-6 col-lg-4 my-3">
							<div class="card mb-2">
								<img src="{{ asset($product->image) }}" width="100" height="250" alt="" class="card-img-top">
								<div class="card-body">
									<h5 class="card-title">
										{{ $product->name}}
									</h5>
									<p class="card-text mb-0">
										Unit Code: 
										{{$product->product_code}}
									</p>
									<p class="{{-- font-weight-bold --}}">Status: {{$product->product_status->name}}</p>
									<p class="card-text mb-0">
										<span class="badge badge-danger text-white">
											{{ $product->category->name }}
										</span>
										{{-- <span class="badge badge-{{$product->product_status_id === 1 ? "danger" : ($product->product_status_id === 2? "info" : "success")}}">
											{{$product->product_status->name}}
										</span> --}}
									</p>
								</div>
								@can('isAdmin')
									<div class="card-footer">
										@include('products.partials.edit-btn')
										@include('products.partials.delete-form')
									</div>
								@endcan
							</div>
						</div>
					@endif
				@endforeach
		
			</div>
		</div>
	</div>
</div>
@endsection